project: 
  type: website
  output-dir: docs

website:
  title: "Leah Lariscy's Wastewater Forecasting Repository"
  navbar:
    left:
      - text: "About Me"
        href: ./aboutme.html
      - text: "Scripts"
        menu:
          - text: "1. Initial Data Cleaning"
            href: ./code/processing/1_initial_cleaning.html
          - text: "2. Data Preprocessing"
            href: ./code/processing/2_preprocessing.html
          - text: "3. Exploratory Time Series Analysis"
            href: ./code/analysis/3_exploratory_timeseries.html
          - text: "4. Univariate Linear Regressions"
            href: ./code/analysis/4_univariate_regressions.html
    right:
      - icon: github 
        href: https://github.com/lmlariscy/WW_Forecasting        

format:
  html:
    theme: pulse
    css: styles.css
    toc: FALSE


